name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Menjalankan deploy setiap kali kamu push ke branch main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install, build, and upload with Astro
        uses: withastro/action@v3 # Action otomatis dari Astro
        # Jika kamu menggunakan pnpm atau yarn, bisa dikonfigurasi di sini